server:
  port: 8099
  session-timeout: 60 # session 超时时间/分钟，默认是30
  tomcat:
    uri-encoding: utf-8 # 设置tomcat编码

# database-1.cwwxcociqa8v.eu-west-1.rds.amazonaws.com yyj123456  localhost Yyj188706

# http://hello.eu-west-1.elasticbeanstalk.com/
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/android?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Yyj188706
  thymeleaf:
    cache: false
    prefix:  classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    mode: LEGACYHTML5
  #这个是关键，放开springboot对静态资源的拦截
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations:  classpath:/templates/,classpath:/static/image/,classpath:/static/

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # The path where the configuration mapper file is located
  type-aliases-package: com.yang.manet.entity # Configure all class aliases under this package
